# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "8a7c80d125485cbe5cef3ba1a9228d44"
name = "Ebaatli"
application_url = "https://ebaatli.com/app/"
embedded = true

[webhooks]
api_version = "2026-01"

[[webhooks.subscriptions]]
compliance_topics = ["customers/data_request"]
uri = "https://ebaatli.com/webhooks/shopify/customers/data_request"

[[webhooks.subscriptions]]
compliance_topics = ["customers/redact"]
uri = "https://ebaatli.com/webhooks/shopify/customers/redact"

[[webhooks.subscriptions]]
compliance_topics = ["shop/redact"]
uri = "https://ebaatli.com/webhooks/shopify/shop/redact"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_checkouts,read_checkouts,read_customers,write_customers,write_order_edits,read_order_edits,customer_write_customers,customer_read_orders,customer_write_orders"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ "https://ebaatli.com/shopify/callback" ]
